### ISSUE TITLE
Ghost block when restarting session

### ISSUE THREAD

**Issue by MattCloward** [eszesbalint/bdstudio#5]
I have a ghost block in my session that I can't seem to get rid of that seems to break all of the features of the tool. 

When I open the tool, it tells me it couldn't load the last session, as usual. After clicking okay, no blocks appear to be present in the visualization, but there is a "bone_block[axis=y]" under the elements section. As soon as I press a key, it appears in the visualization. However, I am unable to select it to alter it in anyway and if I try to delete it, the program loads indefinitely. Attempting to duplicate the block leads to the same result of indefinite loading.

I am also unable to load or create any new blocks (ex: for dirt it says "couldn't load dirt!")

I have tried deleting cookies, but that didn't work. The only solution I have found is to open the program in an incognito window and that brings everything back to normal. Any ideas what might be going on?

Here is the file I get when downloading the file. The name of the file is the original name when I downloaded it, I just changed the extension so I could upload it.
[bone_block[axis=y].txt](https://github.com/eszesbalint/bdstudio/files/11770987/bone_block.axis.y.txt)

**Comment by eszesbalint** [comment]
It seems like that session was created in an earlier version prior to Beta 1.1, and the project structure has changed since. If you want to get rid of that session, just click on New Project. BDStudio saves your session to your local storage each time the editor closes, so if you create a new project and hit refresh it will replace the erroneous session.

**Comment by MattCloward** [comment]
That fixed it, thank you!
